### ISSUE TITLE
command.py module returning a TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by dgmorrisjr** [HubbleStack/Nova#147]
Just starting to use this module.  Read the docstring in the py file to get started.

Here are the first two entries I created in the stig profile i'm creating:

```
command:
  rlogind_must_not_be_running:
    data:
      Red Hat Enterprise Linux Server-6:
        tag:     V-38602
        commands:
          - 'chkconfig rlogin --list':
            match_output:       'error reading information on service rlogin: No such file or directory'
            match_output_regex: False
            fail_if_matched:    False
    description: (HIGH) The rlogin service must not be running.

  audit_loading_and_unloading_dynamic_kernel_modules:
    data:
      Red Hat Enterprise Linux Server-6:
        tag:     V-38580
        commands:
          - 'egrep -e "(-w |-F path=)/sbin/insmod" /etc/audit/audit.rules':
            #match_output:
            match_output_regex: False
            fail_if_matched:    False
        aggregation: 'and'
    description: |
      (MEDIUM) The audit system must be configured to audit the loading and
      unloading of dynamic kernel modules.
```

NOTE: in the V-38580 block above, i tried with the `match_output:` uncommented and commented out to see if that had anything to do with the error output.   In that example, the pass condition for the STIG inspection is that the egrep command returns a line.  It's not concerned about the specific line returned because each site could have a different `-k <tag>` on in their `audit.rules` file.

When I run against the first tag, here is the output:

```
 salt \filter hubble.audit stig-rhel6-mac1-classifed V-38602
filter:
    ----------
    Compliance:
        100%
    Errors:
        |_
          ----------
          /modules/command.py:
              ----------
              data:
                  TypeError: argument of type 'NoneType' is not iterable
              error:
                  exception occurred
    Success:
        |_
          ----------
          description:
              (High) The rlogind service must not be running.
          module:
              service
          name:
              rlogin
          tag:
              V-38602
          type:
              blacklist
```

When I try to run against the 2nd entry in the profile, here is the output:

```
# salt \filter hubble.audit stig-rhel6-mac1-classifed V-38580
filter:
    ----------
    Errors:
        |_
          ----------
          /modules/command.py:
              ----------
              data:
                  TypeError: argument of type 'NoneType' is not iterable
              error:
                  exception occurred
```

If I manually run the command for the 2nd entry using salt's `cmd.run` module, here is the output

```
# salt \filter cmd.run 'egrep -e "(-w |-F path=)/sbin/insmod" /etc/audit/audit.rules'
filter:
    -w /sbin/insmod -p x -k modules
```

**Comment by dgmorrisjr** [comment]
Here is the output from the minion in debug mode:

```
[INFO    ] User root Executing command hubble.audit with jid 20160522155129617427
[DEBUG   ] Command details {'tgt_type': 'glob', 'jid': '20160522155129617427', 'tgt': 'filter', 'ret': '', 'user': 'root', 'arg': ['stig-rhel6-mac1-classifed', 'V-38580'], 'fun': 'hubble.audit'}
[INFO    ] Starting a new job with PID 16662
[DEBUG   ] LazyLoaded hubble.audit
[DEBUG   ] syncing nova modules
[DEBUG   ] LazyLoaded file.remove
[DEBUG   ] LazyLoaded cp.cache_dir
[DEBUG   ] Re-using SAuth for ('/etc/salt/pki/minion', 'filter', 'tcp://192.168.50.51:4506')
[INFO    ] Caching directory 'hubblestack_nova/' for environment 'base'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/com.redhat.rhsa-RHEL6.xml'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/com.redhat.rhsa-RHEL6.xml'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/modules/command.py'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/modules/command.py'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/modules/cve_scan.py'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/modules/cve_scan.py'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/modules/firewall.py'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/modules/firewall.py'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/modules/grep.py'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/modules/grep.py'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/modules/netstat.py'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/modules/netstat.py'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/modules/pkg.py'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/modules/pkg.py'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/modules/service.py'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/modules/service.py'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/modules/stat.py'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/modules/stat.py'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/modules/sysctl.py'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/modules/sysctl.py'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/stig-rhel6-mac1-classifed.yaml'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/stig-rhel6-mac1-classifed.yaml'
[DEBUG   ] loading nova modules
[DEBUG   ] Error loading nova./modules/cve_scan.py: This module requires Linux and the oscap binary
[INFO    ] Executing command 'egrep -e "(-w |-F path=)/sbin/insmod" /etc/audit/audit.rules' in directory '/root'
[DEBUG   ] output: -w /sbin/insmod -p x -k modules
[ERROR   ] Exception occurred in nova module:
[ERROR   ] Traceback (most recent call last):
  File "/var/cache/salt/minion/extmods/modules/hubble.py", line 154, in audit
    ret = func(data_list, tags, verbose=verbose)
  File "/var/cache/salt/minion/files/base/hubblestack_nova/modules/command.py", line 108, in audit
    if 'match_output' in command_args:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by dgmorrisjr** [comment]
And i did a pull from the hubblestack nova develop branch before starting today

**Comment by basepi** [comment]
I think the problem is an indentation issue in your yaml.

The arguments under the command must be indented further, otherwise yaml interprets it as part of the same dictionary, and sets the command value to None. This is a pretty common issue with salt as well; in fact there's a dedicated entry in the FAQ: https://docs.saltstack.com/en/latest/topics/troubleshooting/yaml_idiosyncrasies.html#indentation

```
command:
  rlogind_must_not_be_running:
    data:
      Red Hat Enterprise Linux Server-6:
        tag:     V-38602
        commands:
          - 'chkconfig rlogin --list':
              match_output:       'error reading information on service rlogin: No such file or directory'
              match_output_regex: False
              fail_if_matched:    False
    description: (HIGH) The rlogin service must not be running.

  audit_loading_and_unloading_dynamic_kernel_modules:
    data:
      Red Hat Enterprise Linux Server-6:
        tag:     V-38580
        commands:
          - 'egrep -e "(-w |-F path=)/sbin/insmod" /etc/audit/audit.rules':
              #match_output:
              match_output_regex: False
              fail_if_matched:    False
        aggregation: 'and'
    description: |
      (MEDIUM) The audit system must be configured to audit the loading and
      unloading of dynamic kernel modules.
```

**Comment by dgmorrisjr** [comment]
Okay - i'll try that out

Thanks,

Dan Morris
443-992-2848

**Comment by basepi** [comment]
@dgmorrisjr Since I never heard back from you here, I'm going to assume it was an indentation issue. Please comment if that's not the case.
