### ISSUE TITLE
spm local install hubblestack_nova-latest.spm stack traces on 2016.3.1

### ISSUE THREAD

**Issue by jrporcaro** [HubbleStack/Nova#191]
if I follow the SPM Install instructions it fails with the following: 

[root@jpsalt vagrant]# spm local install ./hubblestack_nova-latest.spm
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
KeyError: "filename '/FORMULA' not found"
Traceback (most recent call last):
  File "/bin/spm", line 12, in <module>
    salt_spm()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 489, in salt_spm
    spm.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/spm.py", line 34, in run
    client.run(self.args)
  File "/usr/lib/python2.7/site-packages/salt/spm/**init**.py", line 103, in run
    self._local(args)
  File "/usr/lib/python2.7/site-packages/salt/spm/__init__.py", line 140, in _local
    self._local_install(args)
  File "/usr/lib/python2.7/site-packages/salt/spm/__init__.py", line 164, in _local_install
    formula_ref = formula_tar.extractfile('{0}/FORMULA'.format(name))
  File "/usr/lib64/python2.7/tarfile.py", line 2111, in extractfile
    tarinfo = self.getmember(member)
  File "/usr/lib64/python2.7/tarfile.py", line 1796, in getmember
    raise KeyError("filename %r not found" % name)
KeyError: "filename '/FORMULA' not found"
Traceback (most recent call last):
  File "/bin/spm", line 12, in <module>
    salt_spm()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 489, in salt_spm
    spm.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/spm.py", line 34, in run
    client.run(self.args)
  File "/usr/lib/python2.7/site-packages/salt/spm/__init__.py", line 103, in run
    self._local(args)
  File "/usr/lib/python2.7/site-packages/salt/spm/__init__.py", line 140, in _local
    self._local_install(args)
  File "/usr/lib/python2.7/site-packages/salt/spm/__init__.py", line 164, in _local_install
    formula_ref = formula_tar.extractfile('{0}/FORMULA'.format(name))
  File "/usr/lib64/python2.7/tarfile.py", line 2111, in extractfile
    tarinfo = self.getmember(member)
  File "/usr/lib64/python2.7/tarfile.py", line 1796, in getmember
    raise KeyError("filename %r not found" % name)
KeyError: "filename '/FORMULA' not found"

Does the Formula directory you build from have a FORMULA file? 

**sample FORMULA file:**
name: php
os: RedHat, Debian, Ubuntu, openSuse
os_family: RedHat, Debian, Suse
dependencies: None
version: 201607
release: 1
summary: Sample Formula for installing php
description: Sample Formula for installing php

**Comment by cedwards** [comment]
@jrporcaro - I discovered this just yesterday myself, but I wonder if it's actually within SPM itself. It looks like installing the versioned package works without a Traceback. eg;

```
wget https://spm.hubblestack.io/2016.7.0_RC1/hubblestack_nova-2016.7.0_RC1-1.spm
spm local install hubblestack_nova-2016.7.0_RC1-1.spm
```

I'll ping Joseph about it in more detail.

**Comment by jrporcaro** [comment]
that may be an SPM issue. Thanks.

On Thu, Jul 14, 2016 at 11:15 AM, Christer Edwards <notifications@github.com

> wrote:
> 
> @jrporcaro https://github.com/jrporcaro - I discovered this just
> yesterday myself, but I wonder if it's actually within SPM itself. It looks
> like installing the versioned package works without a Traceback. eg;
> 
> wget https://spm.hubblestack.io/2016.7.0_RC1/hubblestack_nova-2016.7.0_RC1-1.spm
> spm local install hubblestack_nova-2016.7.0_RC1-1.spm
> 
> I'll ping Joseph about it in more detail.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/HubbleStack/Nova/issues/191#issuecomment-232730964,
> or mute the thread
> https://github.com/notifications/unsubscribe/AHUIFffUGalz0up43ceg0KefdOVz1ps_ks5qVm68gaJpZM4JMkji
> .

## 

Jeff Porcaro
VP, Engineering
SaltStack

**Comment by cedwards** [comment]
I'm going to close this as an upstream bug. The documentation has been updated to reflect working around this issue.
