### ISSUE TITLE
Splunk indexer should be able to accept an array of parameters

### ISSUE THREAD

**Issue by zxjinn** [HubbleStack/Nova#247]
Same goes for Pulsar.

When specifying an array of indexers it throws an error

```
[INFO    ] Options: {"index": "hubble_audit", "token": "TOOOP-SEEC-REET-TOE-KENNNNN", "sourcetype": "hubble_audit", "indexer": ["hostname1.fqdn.tld", "hostname2.fqdn.tld"]}
[ERROR   ] Unhandled exception running hubble.audit
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/utils/schedule.py", line 557, in handle_func
    self.returners[ret_str](ret)
  File "/var/cache/salt/minion/extmods/returners/splunk_nova_return.py", line 49, in returner
    hec = http_event_collector(http_event_collector_key, http_event_collector_host)
  File "/var/cache/salt/minion/extmods/returners/splunk_nova_return.py", line 204, in __init__
    self.server_uri = "".join(buildURI)
TypeError: sequence item 1: expected string, list found
```

I would expect it to jump randomly between all entries for load balancing, until one is found that works (doesn't timeout or otherwise throw an error).

**Comment by zxjinn** [comment]
Opened ticket in [Quasar](https://github.com/HubbleStack/Quasar) instead, makes much more sense for the issue to be there. See https://github.com/HubbleStack/Quasar/issues/23

**Comment by basepi** [comment]
Thanks! I answered over in quasar land.
