### ISSUE TITLE
TypeError issue with Debian

### ISSUE THREAD

**Issue by sainineeraj** [HubbleStack/Nova#248]
I am getting a typeerror while running Hubble.audit. Submitting the issue here as instructed by Christer, I have pasted all logs and versions here
# Wget Nova package

```
root@campstore-paris:~# wget https://spm.hubblestack.io/2016.7.1/hubblestack_nova-2016.7.1-1.spm
--2016-09-14 15:16:01--  https://spm.hubblestack.io/2016.7.1/hubblestack_nova-2016.7.1-1.spm
Resolving spm.hubblestack.io (spm.hubblestack.io)... 104.24.119.108, 104.24.118.108, 2400:cb00:2048:1::6818:766c, ...
Connecting to spm.hubblestack.io (spm.hubblestack.io)|104.24.119.108|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 92340 (90K) [application/octet-stream]
Saving to: ‘hubblestack_nova-2016.7.1-1.spm’

hubblestack_nova-2016.7.1 100%[=====================================>]  90.18K   232KB/s   in 0.4s   

2016-09-14 15:16:01 (232 KB/s) - ‘hubblestack_nova-2016.7.1-1.spm’ saved [92340/92340]
```
# Upgraded Salt & nova install

```
root@campstore-paris:~# apt-get install salt-master
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libasn1-8-heimdal libgssapi3-heimdal libhcrypto4-heimdal libheimbase1-heimdal libheimntlm0-heimdal
  libhx509-5-heimdal libkrb5-26-heimdal libroken18-heimdal libwind0-heimdal python-mako
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  python-croniter python-systemd python-tz salt-common salt-minion
Suggested packages:
  python-augeas
The following NEW packages will be installed:
  python-croniter python-systemd python-tz
The following packages will be upgraded:
  salt-common salt-master salt-minion
3 upgraded, 3 newly installed, 0 to remove and 8 not upgraded.
Need to get 3,741 kB of archives.
After this operation, 3,479 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://ftp.debian.org/debian/ jessie/main python-tz all 2012c+dfsg-0.1 [31.9 kB]
Get:2 http://ftp.debian.org/debian/ jessie/main python-croniter all 0.3.4-1 [10.5 kB]   
Get:3 http://repo.saltstack.com/apt/debian/latest/ jessie/main python-systemd amd64 231-2~bpo8+1 [30.4 kB]
Get:4 http://repo.saltstack.com/apt/debian/latest/ jessie/main salt-minion all 2016.3.3+ds-1 [25.9 kB]
Get:5 http://repo.saltstack.com/apt/debian/latest/ jessie/main salt-master all 2016.3.3+ds-1 [37.4 kB]
Get:6 http://repo.saltstack.com/apt/debian/latest/ jessie/main salt-common all 2016.3.3+ds-1 [3,605 kB]
Fetched 3,741 kB in 2s (1,549 kB/s)      
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package python-tz.
(Reading database ... 21242 files and directories currently installed.)
Preparing to unpack .../python-tz_2012c+dfsg-0.1_all.deb ...
Unpacking python-tz (2012c+dfsg-0.1) ...
Selecting previously unselected package python-croniter.
Preparing to unpack .../python-croniter_0.3.4-1_all.deb ...
Unpacking python-croniter (0.3.4-1) ...
Selecting previously unselected package python-systemd.
Preparing to unpack .../python-systemd_231-2~bpo8+1_amd64.deb ...
Unpacking python-systemd (231-2~bpo8+1) ...
Preparing to unpack .../salt-minion_2016.3.3+ds-1_all.deb ...
Unpacking salt-minion (2016.3.3+ds-1) over (2015.8.3+ds-1) ...
Preparing to unpack .../salt-master_2016.3.3+ds-1_all.deb ...
Unpacking salt-master (2016.3.3+ds-1) over (2015.8.3+ds-1) ...
Preparing to unpack .../salt-common_2016.3.3+ds-1_all.deb ...
Unpacking salt-common (2016.3.3+ds-1) over (2015.8.3+ds-1) ...
Processing triggers for systemd (215-17+deb8u4) ...
Setting up python-tz (2012c+dfsg-0.1) ...
Setting up python-croniter (0.3.4-1) ...
Setting up python-systemd (231-2~bpo8+1) ...
Setting up salt-common (2016.3.3+ds-1) ...
Installing new version of config file /etc/logrotate.d/salt-common ...
Setting up salt-minion (2016.3.3+ds-1) ...

Configuration file '/etc/salt/minion'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** minion (Y/I/N/O/D/Z) [default=N] ? n
Setting up salt-master (2016.3.3+ds-1) ...

Configuration file '/etc/salt/master'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** master (Y/I/N/O/D/Z) [default=N] ? n
root@campstore-paris:~# salt --version
salt 2016.3.3 (Boron)
root@campstore-paris:~# spm local install hubblestack_nova-2016.7.1-1.spm
Installing package from file hubblestack_nova-2016.7.1-1.spm
Proceed? [N/y] y
... installing
```
# Syncing module to minion

```
root@campstore-paris:~# salt mid511b1.frb3.neolane.net saltutil.sync_modules
mid511b1.frb3.neolane.net:
    - modules.hubble
    - modules.oscap
```
# Error running Audit

```
root@campstore-paris:~# salt mid511b1.frb3.neolane.net hubble.audit
mid511b1.frb3.neolane.net:
    TypeError encountered executing hubble.audit: __init__() got an unexpected keyword argument 'opts'. See debug log for more info
```

```
root@campstore-paris:~# salt --versions-report
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.0
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.5 
        machine: x86_64
        release: 2.6.32-openvz-042stab108.6-amd64
         system: Linux
        version: debian 8.5 
```

```
root@campstore-paris:~# cat /etc/debian_version 
8.5
```

**Comment by basepi** [comment]
@sainineeraj Could you please ssh to mid511b1.frb3.neolane.net and run `salt-call -ldebug hubble.audit` and post the results here? The debug output should have the whole traceback, which will be more informative as to the issue.

**Comment by sainineeraj** [comment]
```
[19:38:01][root@mid511b1] ~ # salt-call -ldebug hubble.audit
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: mid511b1.frb3.neolane.net
[DEBUG   ] Configuration file path: /etc/salt/minion
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] The `lspci` binary is not available on the system. GPU grains will not be available.
[WARNING ] Although 'dmidecode' was found in path, the current user cannot execute it. Grains output might not be accurate.
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Mako not available
/usr/lib/python2.6/dist-packages/salt/modules/config.py:251: DeprecationWarning: pillar_opts will default to False in the Lithium release[DEBUG   ] syncing nova modules
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[INFO    ] Caching directory 'hubblestack_nova/' for environment 'base'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/cis/centos-6-level-1-scored-v1.yaml'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/cis/centos-6-level-1-scored-v1.yaml'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/cis/centos-6-level-1-scored-v2-0-1.yaml'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/cis/centos-6-level-1-scored-v2-0-1.yaml'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/cis/centos-7-level-1-scored-v1.yaml'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/cis/centos-7-level-1-scored-v1.yaml'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/cis/centos-7-level-1-scored-v2-1-0.yaml'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/cis/centos-7-level-1-scored-v2-1-0.yaml'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/cis/centos-7-level-1-scored-v2.yaml'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/cis/centos-7-level-1-scored-v2.yaml'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/cis/debian-8-level-1-scored-v1-0-0.yaml'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/cis/debian-8-level-1-scored-v1-0-0.yaml'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/cis/debian-8-level-1-scored-v1.yaml'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/cis/debian-8-level-1-scored-v1.yaml'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/cis/rhels-6-level-1-scored-v1.yaml'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/cis/rhels-6-level-1-scored-v1.yaml'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/cis/rhels-6-level-1-scored-v2-0-1.yaml'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/cis/rhels-6-level-1-scored-v2-0-1.yaml'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/cis/rhels-7-level-1-scored-v1.yaml'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/cis/rhels-7-level-1-scored-v1.yaml'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/cis/rhels-7-level-1-scored-v2-1-0.yaml'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/cis/rhels-7-level-1-scored-v2-1-0.yaml'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/cis/rhelw-7-level-1-scored-v1.yaml'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/cis/rhelw-7-level-1-scored-v1.yaml'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/cis/rhelw-7-level-1-scored-v2-1-0.yaml'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/cis/rhelw-7-level-1-scored-v2-1-0.yaml'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/cis/ubuntu-1404-level-1-scored-v1-0-0.yaml'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/cis/ubuntu-1404-level-1-scored-v1-0-0.yaml'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/cis/ubuntu-1404-level-1-scored-v1.yaml'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/cis/ubuntu-1404-level-1-scored-v1.yaml'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/cis/windows-2008r2-level-1-scored-v1.yaml'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/cis/windows-2008r2-level-1-scored-v1.yaml'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/cis/windows-2008r2-level-1-scored-v3-0-0.yaml'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/cis/windows-2008r2-level-1-scored-v3-0-0.yaml'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/cis/windows-2012r2-level-1-scored-v1.yaml'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/cis/windows-2012r2-level-1-scored-v1.yaml'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/cis/windows-2012r2-level-1-scored-v2-0-0.yaml'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/cis/windows-2012r2-level-1-scored-v2-0-0.yaml'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/cve/scan-v1.yaml'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/cve/scan-v1.yaml'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/cve/scan-v2-salt.yaml'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/cve/scan-v2-salt.yaml'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/cve/scan-v2.yaml'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/cve/scan-v2.yaml'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/firewall/ssh.yaml'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/firewall/ssh.yaml'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/misc.yaml'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/misc.yaml'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/modules/command.py'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/modules/command.py'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/modules/cve_scan.py'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/modules/cve_scan.py'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/modules/cve_scan_v2.py'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/modules/cve_scan_v2.py'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/modules/firewall.py'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/modules/firewall.py'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/modules/grep.py'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/modules/grep.py'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/modules/netstat.py'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/modules/netstat.py'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/modules/openssl.py'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/modules/openssl.py'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/modules/pkg.py'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/modules/pkg.py'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/modules/pkgng_audit.py'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/modules/pkgng_audit.py'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/modules/service.py'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/modules/service.py'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/modules/stat.py'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/modules/stat.py'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/modules/sysctl.py'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/modules/sysctl.py'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/modules/win_auditpol.py'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/modules/win_auditpol.py'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/modules/win_firewall.py'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/modules/win_firewall.py'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/modules/win_gp.py'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/modules/win_gp.py'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/modules/win_pkg.py'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/modules/win_pkg.py'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/modules/win_reg.py'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/modules/win_reg.py'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/modules/win_secedit.py'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/modules/win_secedit.py'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/network/smtp.yaml'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/network/smtp.yaml'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/network/ssh.yaml'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/network/ssh.yaml'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/samples/dont_blame_nrpe.yaml'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/samples/dont_blame_nrpe.yaml'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/samples/sample_cis.yaml'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/samples/sample_cis.yaml'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/samples/sample_command.yaml'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/samples/sample_command.yaml'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/samples/sample_control.yaml'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/samples/sample_control.yaml'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/samples/sample_firewall.yaml'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/samples/sample_firewall.yaml'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/samples/sample_openssl.yaml'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/samples/sample_openssl.yaml'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/stig/rhel-6-mac-1-classified.yaml'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/stig/rhel-6-mac-1-classified.yaml'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://hubblestack_nova/top.nova'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'hubblestack_nova/top.nova'
[DEBUG   ] loading nova modules
Passed invalid arguments: __init__() got an unexpected keyword argument 'opts'
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/salt/cli/caller.py", line 129, in call
    ret['return'] = func(*args, **kwargs)
  File "/var/cache/salt/minion/extmods/modules/hubble.py", line 110, in audit
    debug=debug)
  File "/var/cache/salt/minion/extmods/modules/hubble.py", line 339, in top
    load()
  File "/var/cache/salt/minion/extmods/modules/hubble.py", line 483, in load
    __nova__ = NovaLazyLoader()
  File "/var/cache/salt/minion/extmods/modules/hubble.py", line 563, in __init__
    tag='nova')
TypeError: __init__() got an unexpected keyword argument 'opts'
```

**Comment by sainineeraj** [comment]
@basepi - thanks for looking into it! uploaded results from debug

**Comment by basepi** [comment]
Can you please run the following in a python shell?

```
[root@bslm-022 ~]# python
Python 2.7.5 (default, Nov 20 2015, 02:00:19)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import salt.loader
>>> salt.loader.__file__
'/usr/lib/python2.7/site-packages/salt/loader.pyc'
```

Yours should show python 2.6 when python starts. What I'm looking for is the path at the end. Mine shows `/usr/lib/python2.7/site-packages/salt/loader.pyc`, yours could show differently.

I want you to go to that path, but to the .py file, not the .pyc file, and post the contents of that file here. Something odd is going on with your salt install, I'm not sure what it is yet.

**Comment by sainineeraj** [comment]
[22:52:51][root@mid511b1] ~ # python
Python 2.6.6 (r266:84292, Aug 12 2014, 07:57:00) 
[GCC 4.4.5] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > import salt.loader
> > > salt.loader.**file**
> > > '/usr/lib/python2.6/dist-packages/salt/loader.pyc'

**Comment by basepi** [comment]
Can you show me the contents of `/usr/lib/python2.6/dist-packages/salt/loader.py` please?

**Comment by sainineeraj** [comment]
@basepi  here you go:

https://gist.github.com/basepi/8978cceba3502bbef7d592971265545e

(Edited to replace long content with a gist)

**Comment by basepi** [comment]
Whoops, probably should have had you gist that....

**Comment by basepi** [comment]
Well, that file does match your error. However, it doesn't match Salt v2016.3.3. I'm not sure where that file came from, trying to track it down.

**Comment by basepi** [comment]
As we discussed on Slack, your minions need to be on salt 2015.5 or greater.
